server:
  port: 8080
spring:
  redis:
    cluster:
      nodes:
        - 10.7.3.168:6374
        - 10.7.3.168:6375
        - 10.7.3.168:6376
        - 10.7.3.168:6377
        - 10.7.3.168:6378
        - 10.7.3.168:6379
    #host: 10.7.3.168
    #port: 6379
    #database: 0
    #password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0