server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.7.3.168:3306/activiti_demo?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  mapper-locations:  classpath:mapper/*.xml

