spring:
  application:
    name: sprint-cloud-eureka-server-center

server:
  port: 8761
  #port: 8762 #集群方式多开

eureka:
  instance:
    #prefer-ip-address: false #使用主机名来定义注册中心的地址，集群使用
    hostname: localhost #需要搭建eureka集群的话，那么eureka.instance.hostname不能重复，否则集群失败，所以不能为localhost或者ip地址
    #hostname: server1 #需要修改host文件127.0.0.1 server1 （linux的host在/etc/host，mac的在/private/etc，windows的在C:/windows/system32/drivers/etc）
    #hostname: server2                 #127.0.0.1 server2

  server:
    enable-self-preservation: false #开发时关闭自我保护，确保注册中心中不可用的实例被及时的剔除
  client:
    registerWithEureka: false # 禁止注册到eureka中心, 当前这个应用就是Eureka Server，所以不需要把自己注册（集群为true,默认不写为true）
    fetchRegistry: false # 禁止从中心获取文件, 这是一个单点的Eureka Server，不需要同步其他Eureka Server节点的数据，设为false（集群为true,默认不写为true）
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
