server:
  port: 8080
spring:
  session:
    store-type: redis #session存储格式为redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
  datasource: #MySql数据库参数配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zedm32w3746975j8mo.mysql.rds.aliyuncs.com/japedb?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: jape
    password: Jape970501
    #url: jdbc:mysql://127.0.0.1:3306/japedb?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    #username: root
    #password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置sql打印日志
      #global-config:
      #db-config:
    #update-strategy: not_null
    cache-enabled: true