server:
  port: 8080
spring:
  session:
    store-type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zedm32w3746975j8mo.mysql.rds.aliyuncs.com/japedb?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: jape
    password: Jape970501
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl