server:
  port: 8080

mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.jape.shardingjdbcdemo.entity

# 单分表
sharding:
  jdbc:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.7.3.168:3306/jape01
        username: root
        password: 123456
    config:
      props:
        sql.show: true
      sharding:
        tables:
          t_user:  #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.t_user${0..1}    #数据节点,均匀分布
            table-strategy:  #分表策略
              inline: #行表达式
                sharding-column: sex
                algorithm-expression: t_user${sex % 2}  #按模运算分配