spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 4096MB

#优雅关闭服务
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, shutdown