server:
  port: 80
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: testPath
          uri: lb://EUREKA-CLIENT-PROVIDER
          predicates:
            - Path=/testCluster
        - id: testPathAndAfter
          uri: lb://EUREKA-CLIENT-PROVIDER
          predicates:
            - Path=/testTimeout
            - After=2020-06-22T16:10:00+08:00[Asia/Shanghai]
        - id: baidu
          uri: http://baidu.com
          predicates:
            - Path=/baidu
eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: true #自注册，默认true
    #fetch-registry: true #同步Eureka Server节点，默认true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
