server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.7.3.168:3306/activiti_demo?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
#    process-definition-location-suffixes: #流程文件格式
#      - **.bpmn
#     - **.bpmn20.xml
    history-level: full
    db-history-used: true
    db-identity-used: false
    async-executor-activate: false
    mail-server-host: smtp.qq.com
    mail-server-port: 587
    mail-server-user-name: 1143828481@qq.com
    mail-server-default-from: 1143828481@qq.com
    mail-server-password: civlhtfqkmlnjcia

mybatis:
  mapper-locations:  classpath:mapper/*.xml

