spring:
  application:
    name: eureka-client-consumer

server:
  port: 80

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ #eureka注册中心集群方式